"""游戏规则集接口。流程层只依赖本模块，不依赖具体玩法。"""

from dataclasses import dataclass
from typing import Protocol

from app.models.game import GamePlayer, Meld, TileType
from app.rules.fans import FanContext, FanEvaluation


@dataclass(frozen=True)
class ClaimCapabilities:
    can_peng: bool = False
    can_gang: bool = False
    can_hu: bool = False
    chi_options: tuple[dict, ...] = ()


class GameRuleSet(Protocol):
    code: str
    base_score: int
    horse_count: int
    supports_chi: bool

    def create_wall(self) -> list[TileType]: ...
    def is_flower_tile(self, tile: TileType) -> bool: ...
    def is_joker_tile(self, tile: TileType) -> bool: ...
    def is_claimable_tile(self, tile: TileType) -> bool: ...
    def should_auto_win_on_flowers(self, count: int) -> bool: ...
    def resolve_win_tile(self, winner: GamePlayer, options: dict) -> TileType: ...
    def is_winning_hand(self, tiles: list[TileType], exposed_meld_count: int = 0) -> bool: ...
    def waiting_tiles(self, tiles: list[TileType], exposed_meld_count: int = 0) -> list[TileType]: ...
    def matching_count(self, tiles: list[TileType], tile: TileType) -> int: ...
    def concealed_kongs(self, tiles: list[TileType]) -> list[TileType]: ...
    def can_added_kong(self, hand: list[TileType], melds: list[Meld], tile: TileType) -> bool: ...
    def can_rob_kong(self, tiles: list[TileType], tile: TileType,
                     exposed_meld_count: int = 0) -> bool: ...
    def claim_capabilities(self, hand: list[TileType], tile: TileType) -> ClaimCapabilities: ...
    def draw_horses(self, wall: list[TileType], amount: int | None = None, seat: int = 0) -> dict: ...
    def evaluate_fans(self, context: FanContext) -> FanEvaluation: ...
    def score_hand(self, context: FanContext) -> dict: ...
